# Generated by Django 2.1.7 on 2019-10-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('models_name', models.CharField(default='', max_length=30, verbose_name='模块名')),
                ('record_id', models.BigIntegerField(default=0, verbose_name='被记录的实体id')),
                ('user_name', models.CharField(default='', max_length=30, verbose_name='操作用户名')),
                ('behavior_type', models.PositiveSmallIntegerField(default=0, verbose_name='操作类型，1为新增，2为修改，3为删除')),
                ('content', models.TextField(default='', verbose_name='日志内容')),
                ('record_time', models.DateTimeField(verbose_name='业务记录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='日志产生时间')),
            ],
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['models_name', 'record_id'], name='BusinessLog_models__65386b_idx'),
        ),
    ]
